import { useEffect, useMemo, useState } from "react";
import { ArrowRight, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { Link } from "wouter";
import { MapView } from "@/components/Map";
import { supabase, formatZar, type Business, type Service } from "@/lib/supabase";

const categories = ["All places", "Beauty", "Wellness", "Fitness", "Food & drink", "Barber", "Plumbing", "Other"];
const art = ["✿", "◌", "✦", "◒"];

export default function Home() {
  const [businesses, setBusinesses] = useState<Business[]>([]); const [services, setServices] = useState<Service[]>([]); const [query, setQuery] = useState(""); const [city, setCity] = useState("Pietermaritzburg"); const [category, setCategory] = useState("All places"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { const [{ data: b, error: be }, { data: s, error: se }] = await Promise.all([supabase.from("businesses").select("id,name,category,city,address,whatsapp,description,is_active,rating_avg,price_from").eq("is_active", true).eq("is_suspended", false).order("name"), supabase.from("services").select("id,business_id,name,price,duration_minutes,is_active").eq("is_active", true)]); if (be || se) setError("Service temporarily unavailable. Please retry."); setBusinesses(b ?? []); setServices(s ?? []); setLoading(false); })(); }, []);
  const filtered = useMemo(() => businesses.filter((business) => { const text = `${business.name} ${business.category} ${business.city} ${business.address} ${business.description}`.toLowerCase(); const matchesCategory = category === "All places" || (category === "Other" ? !["Beauty", "Wellness", "Fitness", "Food & drink", "Barber", "Plumbing"].includes(business.category) : business.category === category); return (!query || text.includes(query.toLowerCase())) && (!city || (business.city ?? "").toLowerCase().includes(city.toLowerCase())) && matchesCategory; }), [businesses, category, city, query]);
  const servicesFor = (id: string) => services.filter((service) => service.business_id === id);
  return <div className="min-h-screen bg-[#f8f8f6] text-[#171717]" id="top">
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_28%,rgba(168,230,207,.55),transparent_30%),radial-gradient(circle_at_15%_90%,rgba(233,48,94,.12),transparent_28%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28 lg:pt-28"><div><p className="eyebrow">Local services, made simple</p><h1 className="hero-title">Your day,<br /><span className="pink">booked better.</span></h1><p className="hero-copy">Find trusted local businesses, see what they offer, and book a time that fits your life. No back-and-forth. Just a better way to make plans.</p><div className="flex flex-wrap gap-3"><a className="button-pink" href="#explore">Explore local places <ArrowRight className="size-4" /></a><Link className="button-light" href="/business-register.html">List your business</Link></div></div><div className="relative min-h-[25rem]"><div className="art-note"><b>Easy booking</b><small>Find a time, not a thread</small></div><div className="art-main"><span>✿</span></div><div className="art-info"><b>Live PMB places</b><small>Real businesses · Pietermaritzburg</small><br /><span className="pink">Book when it suits you →</span></div></div></div></section>
    <section className="section" id="explore"><div className="section-heading"><div><p className="eyebrow">Start with a feeling</p><h2>What are you<br />looking for?</h2></div><p>Good plans start with a little inspiration. Find your next local favourite in Pietermaritzburg.</p></div><div className="search-panel"><label className="search-field"><Search className="size-5 text-[#E9305E]" /><input placeholder="Search businesses or services" value={query} onChange={(e) => setQuery(e.target.value)} /></label><label className="search-field"><MapPin className="size-5 text-[#E9305E]" /><input value={city} onChange={(e) => setCity(e.target.value)} aria-label="Choose city" /></label><button className="button-pink" onClick={() => document.getElementById("places")?.scrollIntoView({ behavior: "smooth" })}>Find a time <ArrowRight className="size-4" /></button></div><div className="chips">{categories.map((item) => <button key={item} className={`chip ${category === item ? "active" : ""}`} onClick={() => setCategory(item)}>{item}</button>)}<button className="chip" onClick={() => setCategory("Other")}>+ More</button></div></section>
    <section className="section map-section"><div className="section-heading"><div><p className="eyebrow">Find something nearby</p><h2>Local places,<br /><span className="pink">close to home.</span></h2></div><p>Search the map for places around Pietermaritzburg.</p></div><div className="map-shell relative"><MapView initialCenter={{ lat: -29.6006, lng: 30.3794 }} initialZoom={13} className="h-[370px] rounded-[1.5rem]" /><div className="map-overlay"><p className="eyebrow">Search places</p><div className="map-search"><Search className="size-4 text-[#E9305E]" /><input aria-label="Search places on map" placeholder="Search places" value={query} onChange={(e) => setQuery(e.target.value)} /><button onClick={() => document.getElementById("places")?.scrollIntoView({ behavior: "smooth" })}>Search</button></div><small>Explore the map and browse matching places below.</small></div></div></section>
    <section className="section community"><div className="community-card"><div><p className="eyebrow">A little more local</p><h2>Good local things<br />are coming.</h2><p>We’re building a calmer way to find the people and places that make Pietermaritzburg feel like home.</p></div><div className="community-art">✦</div></div></section>
    <section className="section" id="places"><div className="section-heading"><div><p className="eyebrow">Around you</p><h2>Places ready<br /><span className="pink">when you are.</span></h2></div><div className="flex items-center gap-2 text-sm font-bold text-black/55"><SlidersHorizontal className="size-4" />{filtered.length} places</div></div>{error && <div className="panel mb-6 bg-[#fff2d8]">{error} <button className="font-bold underline" onClick={() => window.location.reload()}>Retry</button></div>}{loading ? <div className="cards"><div className="loading-card" /><div className="loading-card" /><div className="loading-card" /></div> : filtered.length === 0 ? <div className="panel empty">No local places matched that search yet.</div> : <div className="cards">{filtered.map((business, index) => <BusinessCard key={business.id} business={business} services={servicesFor(business.id)} index={index} />)}</div>}</section>
    <section className="section how"><div className="section-heading"><div><p className="eyebrow">The simple way</p><h2>Make a plan<br /><span className="pink">you’ll keep.</span></h2></div><p>Choose a place, find a time, and keep your local plans in one calm place.</p></div><div className="steps"><Step n="01" title="Choose a place" text="Browse real local businesses and what they offer." /><Step n="02" title="Find your time" text="See live availability without the back-and-forth." /><Step n="03" title="Book with clarity" text="Confirm your appointment and pay at venue." /></div></section>
  </div>;
}
function BusinessCard({ business, services, index }: { business: Business; services: Service[]; index: number }) { return <article className="service-card"><div className={`service-image image-${index % 4}`}>{art[index % art.length]}</div><div className="service-body"><p className="eyebrow">{business.category} · {business.city}</p><h3>{business.name}</h3><p>{business.description}</p><div className="service-meta"><span><span className="price">From {formatZar(Math.max(20, business.price_from))}</span></span><Link className="button-pink small" href={`/business.html?id=${business.id}`}>Book from <ArrowRight className="size-4" /></Link></div><p className="mt-3 text-xs text-black/45">{services.length} services · {business.address}</p></div></article>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="step-card"><span>{n}</span><h3>{title}</h3><p>{text}</p></div>; }
